/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_javahjni_MainActivity */

#ifndef _Included_com_javahjni_MainActivity
#define _Included_com_javahjni_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_javahjni_MainActivity
 * Method:    getS
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_javahjni_MainActivity_getS
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
